CREATE TABLE Cliente IF NOT EXISTS(
	IDCliente INTEGER(11) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Cognome VARCHAR(30) NOT NULL
);

CREATE TABLE Prodotto IF NOT EXISTS(
	IDProdotto INTEGER(11) PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL
);

CREATE TABLE Ordine IF NOT EXISTS(
	IDCliente INTEGER(11),
	IDProdotto INTEGER(11),
	PRIMARY KEY(IDCliente, IDProdotto)
);

CREATE TABLE Ingrediente IF NOT EXISTS(
	IDIngrediente INTEGER(11) PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL
);

CREATE TABLE CompostoDa IF NOT EXISTS(
	IDProdotto INTEGER(11),
	IDIngrendiente INTEGER(11),
	PRIMARY KEY(IDProdotto, IDIngrendiente)
);

CREATE TABLE Pizzeria IF NOT EXISTS(
	IDPizzeria INTEGER(11) PRIMARY KEY,
	Nome VARCHAR(40) NOT NULL,
	NumeroTelefono VARCHAR(30) NOT NULL,
	CAP VARCHAR(5) NOT NULL,
	Paese VARCHAR(40) NOT NULL,
	Via VARCHAR(50) NOT NULL,
	NumeroCivico INTEGER(5) NOT NULL,
	Asporto BOOLEAN NOT NULL
);

CREATE TABLE Appartiene IF NOT EXISTS(
	IDProdotto INTEGER(11),
	IDPizzeria INTEGER(11),
	PRIMARY KEY(IDProdotto, IDPizzeria)
);

